### ISSUE TITLE
prettier/prettier-svelte in workspace root?

### ISSUE THREAD

**Issue by ewilliam** [Brisklemonade/turbosvelte#1]
hi! wanted to open a discussion but hope here is ok.

wondering why prettier and prettier-svelte is in workspace root? while eslint and eslint-svelte is in project folders?

thanks for this repo! super helpful

**Comment by kamellperry** [comment]
I've been meaning to make a global prettier and eslint config to be used throughout the monorepo so that every project can be linted with one command. I just haven't gotten around to fixing it yet. I will get to it soon though. In the meantime, thank you for using it!

**Comment by ewilliam** [comment]
could you hint at what would that take? so i can get an idea how to set that up and possibly contribute to this.

ie would that be in workspace root or something like rename-eslint-preset?

**Comment by kamellperry** [comment]
It would be configs set at the project root. Then add a global lint script that runs prettier and eslint.
