### ISSUE TITLE
Port problem when running vanilla version...

### ISSUE THREAD

**Issue by maku** [Brisklemonade/turbosvelte#6]
When running `npm run build` in a clean copy of "turbosvelte" I get an error because of the default port of the svelte apps...

I had to change the scripts "dev" entries in the package.json files  to define different ports ->  e.g. `svelte-kit dev -p 3200`. 

Then I had the (known) problem of the missing "src/routes" dir in rename-core...

**Comment by kamellperry** [comment]
Thank you for pointing that out. You ran the build script from the project root correct?

**Comment by maku** [comment]
@Brisklemonade yes

**Comment by kamellperry** [comment]
Okay thank you, I will be making updates to the project later today!

**Comment by kamellperry** [comment]
The build issue should be fixed now. As for the port thing I need to look into it later, but for now I put instructions in the readme on how to fix that. Temporary solution for now.
